### PR TITLE
OVAL graphs in the report

### PR DESCRIPTION
**Pull request by Honny1**
This PR  adds OVAL graphs to the report.

Screenshot from 2021-09-07 15-30-05

### CODE REVIEW

**Comment by evgenyz** [comment]
Okay, there is so much visual noise I can't even think straight about it. Give me some time to understand the options.

**Comment by evgenyz** [comment]
But the obvious thing right away: combine `false` + `X` and `true` + `V` in a single label.

**Comment by Honny1** [comment]
Screenshot from 2021-09-09 09-49-13

**Comment by evgenyz** [comment]
Err, now marks on the left seems to be redundant except for `NOT AND` case. Oh, well, we could start with this and improve later.

**Pull request merged**
