### PR TITLE
Initial packaging

### PR DESCRIPTION
**Pull request by evgenyz**

### CODE REVIEW

**Comment by evgenyz** [comment]
We have problems with deps satisfaction on el9 and F32 (could be ignored).

**Comment by Honny1** [comment]
After reading the logs. I found for Fedora 34 is available RPM of `pytest` in version `6.2.2`. In the file, `requirements.txt` is specified version `6.2.4`. I suggest changing the version of `pytest` in the `requirements.txt`.

**Comment by evgenyz** [comment]
> After reading the logs. I found for Fedora 34 is available RPM of `pytest` in version `6.2.2`. In the file, `requirements.txt` is specified version `6.2.4`. I suggest changing the version of `pytest` in the `requirements.txt`.

What are we going to do with el9?

```
+ /usr/bin/python3 -s /usr/lib/rpm/redhat/pyproject_buildrequires.py --generate-extras --python3_pkgversion 3 -t
Handling setuptools >= 40.8 from default build backend
Requirement satisfied: setuptools >= 40.8
   (installed: setuptools 53.0.0)
Handling wheel from default build backend
Requirement satisfied: wheel
   (installed: wheel 0.36.2)
HOOK STDOUT: running egg_info
HOOK STDOUT: creating oscap_report.egg-info
HOOK STDOUT: writing oscap_report.egg-info/PKG-INFO
HOOK STDOUT: writing dependency_links to oscap_report.egg-info/dependency_links.txt
HOOK STDOUT: writing entry points to oscap_report.egg-info/entry_points.txt
HOOK STDOUT: writing requirements to oscap_report.egg-info/requires.txt
HOOK STDOUT: writing top-level names to oscap_report.egg-info/top_level.txt
HOOK STDOUT: writing manifest file 'oscap_report.egg-info/SOURCES.txt'
HOOK STDOUT: reading manifest file 'oscap_report.egg-info/SOURCES.txt'
HOOK STDOUT: reading manifest template 'MANIFEST.in'
HOOK STDOUT: adding license file 'LICENSE'
HOOK STDOUT: writing manifest file 'oscap_report.egg-info/SOURCES.txt'
Handling wheel from get_requires_for_build_wheel
Requirement satisfied: wheel
   (installed: wheel 0.36.2)
Handling tox-current-env >= 0.0.6 from tox itself
Requirement satisfied: tox-current-env >= 0.0.6
   (installed: tox-current-env 0.0.6)
___________________________________ summary ____________________________________
  py39: commands succeeded
  congratulations :)
Handling flake8>=3.8.4 from tox --print-deps-only: py39
Requirement not satisfied: flake8>=3.8.4
Handling pylint>=2.6.0 from tox --print-deps-only: py39
Requirement not satisfied: pylint>=2.6.0
Handling pytest>=6.2.4 from tox --print-deps-only: py39
Requirement not satisfied: pytest>=6.2.4
Handling pytest-cov>=2.10.1 from tox --print-deps-only: py39
Requirement not satisfied: pytest-cov>=2.10.1
Handling tox>=3.20.1 from tox --print-deps-only: py39
Requirement satisfied: tox>=3.20.1
   (installed: tox 3.24.4)
Handling lxml from tox --print-deps-only: py39
Requirement not satisfied: lxml
Handling jinja2 from tox --print-deps-only: py39
Requirement not satisfied: jinja2
HOOK STDOUT: running dist_info
HOOK STDOUT: writing oscap_report.egg-info/PKG-INFO
HOOK STDOUT: writing dependency_links to oscap_report.egg-info/dependency_links.txt
HOOK STDOUT: writing entry points to oscap_report.egg-info/entry_points.txt
HOOK STDOUT: writing requirements to oscap_report.egg-info/requires.txt
HOOK STDOUT: writing top-level names to oscap_report.egg-info/top_level.txt
HOOK STDOUT: reading manifest file 'oscap_report.egg-info/SOURCES.txt'
HOOK STDOUT: reading manifest template 'MANIFEST.in'
HOOK STDOUT: adding license file 'LICENSE'
HOOK STDOUT: writing manifest file 'oscap_report.egg-info/SOURCES.txt'
HOOK STDOUT: creating '/builddir/build/BUILD/openscap-report-0.1.0/oscap_report.dist-info'
HOOK STDOUT: adding license file "LICENSE" (matched pattern "LICEN[CS]E*")
Handling lxml from wheel metadata: Requires-Dist
Requirement not satisfied: lxml
Handling jinja2 from wheel metadata: Requires-Dist
Requirement not satisfied: jinja2
+ RPM_EC=0
++ jobs -p
+ exit 0
Wrote: /builddir/build/SRPMS/openscap-report-0.1.0-0.20220127212752535675.pr44.el9.buildreqs.nosrc.rpm
INFO: Going to install missing dynamic buildrequires
No matches found for the following disable plugin patterns: local, spacewalk, versionlock
Copr repository                                  36 kB/s | 3.3 kB     00:00    
Package python3-devel-3.9.9-4.el9.x86_64 is already installed.
Package python3-devel-3.9.9-4.el9.x86_64 is already installed.
No matching package to install: 'python3dist(flake8) >= 3.8.4'
Package python3-packaging-20.9-4.el9.noarch is already installed.
Package python3-pip-21.2.3-5.el9.noarch is already installed.
No matching package to install: 'python3dist(pylint) >= 2.6'
No matching package to install: 'python3dist(pytest) >= 6.2.4'
Package python3-setuptools-53.0.0-9.el9.noarch is already installed.
Package tox-3.24.4-2.el9.noarch is already installed.
Package python3-tox-current-env-0.0.6-4.el9.noarch is already installed.
Package python3-wheel-1:0.36.2-6.el9.noarch is already installed.
Not all dependencies satisfied
Error: Some packages could not be found.
WARNING: Dnf command failed, retrying, attempt #2, sleeping 10s
No matches found for the following disable plugin patterns: local, spacewalk, versionlock
Copr repository                                  31 kB/s | 3.3 kB     00:00    
Package python3-devel-3.9.9-4.el9.x86_64 is already installed.
Package python3-devel-3.9.9-4.el9.x86_64 is already installed.
No matching package to install: 'python3dist(flake8) >= 3.8.4'
Package python3-packaging-20.9-4.el9.noarch is already installed.
Package python3-pip-21.2.3-5.el9.noarch is already installed.
No matching package to install: 'python3dist(pylint) >= 2.6'
No matching package to install: 'python3dist(pytest) >= 6.2.4'
Package python3-setuptools-53.0.0-9.el9.noarch is already installed.
Package tox-3.24.4-2.el9.noarch is already installed.
Package python3-tox-current-env-0.0.6-4.el9.noarch is already installed.
Package python3-wheel-1:0.36.2-6.el9.noarch is already installed.
Not all dependencies satisfied
Error: Some packages could not be found.
WARNING: Dnf command failed, retrying, attempt #3, sleeping 10s
No matches found for the following disable plugin patterns: local, spacewalk, versionlock
Copr repository                                  30 kB/s | 3.3 kB     00:00    
Package python3-devel-3.9.9-4.el9.x86_64 is already installed.
Package python3-devel-3.9.9-4.el9.x86_64 is already installed.
No matching package to install: 'python3dist(flake8) >= 3.8.4'
Package python3-packaging-20.9-4.el9.noarch is already installed.
Package python3-pip-21.2.3-5.el9.noarch is already installed.
No matching package to install: 'python3dist(pylint) >= 2.6'
No matching package to install: 'python3dist(pytest) >= 6.2.4'
Package python3-setuptools-53.0.0-9.el9.noarch is already installed.
Package tox-3.24.4-2.el9.noarch is already installed.
Package python3-tox-current-env-0.0.6-4.el9.noarch is already installed.
Package python3-wheel-1:0.36.2-6.el9.noarch is already installed.
Not all dependencies satisfied
Error: Some packages could not be found.
```

**Comment by Honny1** [comment]
Important dependencies for testing are `tox`, `pytest` and `pytest-cov`. `pylint` and `flake8` are used for checking code quality. Let's set them as "optional" dependencies and execute tests with them when they are available. 

In the case of `pytest` it is the same as for Fedora 34. But unfortunately `pytest-cov` is broken. There is a problem with the dependencies of `pytest-cov` which we can't affect. So we can ignore this problem.

I changed dependencies and part of the test suite which uses `pylint` and `flake8`  in #46.

**Comment by evgenyz** [comment]
Let's continue in #46.

**Pull request closed without merging**
